---
# tasks file for wso2is

# This assumes Java is already installed

# 1. Unzip product to location
- name: Unpack product distribution
  unarchive: 
    src: wso2is-5.5.0.zip
    dest: /opt

# 2. Apply templates
# TODO

# 3. Add Service definition
- name: Add WSO2 Server service definition
  template: 
    src: wso2service.j2
    dest: /etc/init.d/wso2is
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=r"

# 4. Start server

# - name: Start WSO2 server
#   shell: "./wso2server.sh"
#   args:
#     chdir: "/opt/wso2is-5.5.0/bin/"
#     executable: "/bin/bash"

- name: Start WSO2 service
  service: 
    name: wso2is
    state: started